# Generated by Django 3.1.5 on 2021-02-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeButtonModel',
        ),
    ]
