# Generated by Django 3.1.5 on 2021-03-15 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='名無し', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='対象記事'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='本文', max_length=255),
        ),
    ]
