# Generated by Django 3.1.5 on 2021-03-15 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210315_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='対象記事'),
        ),
    ]
